namespace: kubeflow
resources:
- deployment.yaml
- service.yaml
- envoyfilter.yaml
- istio

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mlflow.lua
  files:
  - lib/json.lua
  - lib/url.lua
  - lib/mlflow.lua